image: barichello/godot-ci:3.3
# Cache imported assets between runs
cache:
  key: import-assets
  paths:
    - .import/
stages:
  - export
  - deploy
variables:
  EXPORT_NAME: titan_tactics

windows:
  stage: export
  script:
    - mkdir -v -p ${EXPORT_NAME}_windows
    - godot -v --export "Windows Desktop" ${EXPORT_NAME}_windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - ${EXPORT_NAME}_windows
  only:
    - master
    - staging

windows_debug:
  stage: export
  script:
    - mkdir -v -p ${EXPORT_NAME}_windows_debug
    - godot -v --export-debug "Windows Desktop" ${EXPORT_NAME}_windows_debug/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - ${EXPORT_NAME}_windows_debug
  only:
  - staging

linux:
  stage: export
  script:
    - mkdir -v -p ${EXPORT_NAME}_linux
    - godot -v --export "Linux/X11" ${EXPORT_NAME}_linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - ${EXPORT_NAME}_linux
  only:
    - master
    - staging

stories_preview:
  stage: export
  script:
    - apt-get -y update
    - apt-get -y install curl
    - apt-get -y install build-essential
    - curl -sL https://deb.nodesource.com/setup_16.x | bash
    - apt-get -y install nodejs
    - npm install -g -s --no-progress yarn
    - cd helpers/converters
    - yarn install
    - yarn triggers ../../scenes/levels
    - cd ../titan_stories
    - yarn install
    - yarn build
    - cd ../..
    - mkdir -v -p ${EXPORT_NAME}_stories_preview
    - godot -v --export "HTML5-Stories-Preview" ${EXPORT_NAME}_stories_preview/$EXPORT_NAME.html
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - ${EXPORT_NAME}_stories_preview
      - helpers/titan_stories/dist
      - helpers/converters/triggers.json
  only:
    - staging

# GitLab Pages Deploy
pages:
  stage: deploy
  dependencies:
    - stories_preview
  script:
    - mkdir -p public/game
    - mkdir -p public/levels/en_US
    - mkdir -p public/levels/nl_NL
    - mv helpers/titan_stories/dist/* ./public
    - mv ${EXPORT_NAME}_stories_preview/** ./public/game
    - cp resources/story/en_US/level*.json ./public/levels/en_US
    - cp resources/story/nl_NL/level*.json ./public/levels/nl_NL
    - cp helpers/converters/triggers.json ./public
  artifacts:
    paths:
      - public
  only:
    - staging

linux_debug:
  stage: export
  script:
    - mkdir -v -p ${EXPORT_NAME}_linux_debug
    - godot -v --export-debug "Linux/X11" ${EXPORT_NAME}_linux_debug/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - ${EXPORT_NAME}_linux_debug
  only:
  - staging

mac:
  stage: export
  script:
    - mkdir -v -p ${EXPORT_NAME}_mac
    - godot -v --export "Mac OSX" ${EXPORT_NAME}_mac/$EXPORT_NAME.zip
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - ${EXPORT_NAME}_mac
  only:
    - master
    - staging

mac_debug:
  stage: export
  script:
    - mkdir -v -p ${EXPORT_NAME}_mac_debug
    - godot -v --export-debug "Mac OSX" ${EXPORT_NAME}_mac_debug/$EXPORT_NAME.zip
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - ${EXPORT_NAME}_mac_debug
  only:
  - staging

# Itch.io Deploy
itchio:linux:
  stage: deploy
  script:
    - butler push ./${EXPORT_NAME}_linux $ITCHIO_USERNAME/$ITCHIO_GAME:linux
  dependencies:
    - linux
  only:
    - master

itchio:windows:
  stage: deploy
  script:
    - butler push ./${EXPORT_NAME}_windows $ITCHIO_USERNAME/$ITCHIO_GAME:windows
  dependencies:
    - windows
  only:
    - master

itchio:macosx:
  stage: deploy
  script:
    - butler push ./${EXPORT_NAME}_mac $ITCHIO_USERNAME/$ITCHIO_GAME:mac
  dependencies:
    - mac
  only:
    - master
