image: barichello/godot-ci:3.2.1
# Cache imported assets between runs
cache:
  key: import-assets
  paths:
    - .import/
stages:
  - export
  - deploy
variables:
  EXPORT_NAME: titan_tactics

windows:
  stage: export
  script:
    - mkdir -v -p ${EXPORT_NAME}_windows
    - godot -v --export "Windows Desktop" ${EXPORT_NAME}_windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - ${EXPORT_NAME}_windows

linux:
  stage: export
  script:
    - mkdir -v -p ${EXPORT_NAME}_linux
    - godot -v --export "Linux/X11" ${EXPORT_NAME}_linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - ${EXPORT_NAME}_linux

mac:
  stage: export
  script:
    - mkdir -v -p ${EXPORT_NAME}_mac
    - godot -v --export "Mac OSX" ${EXPORT_NAME}_mac/$EXPORT_NAME.zip
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - ${EXPORT_NAME}_mac

web:
  stage: export
  script:
    - mkdir -v -p ${EXPORT_NAME}_web
    - echo 'quality/driver/driver_name="GLES2"' >> project.godot
    - godot -v --export "HTML5" ${EXPORT_NAME}_web/index.html
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - ${EXPORT_NAME}_web

# GitLab Pages Deploy
pages:
  stage: deploy
  dependencies:
    - web
  script:
    - mkdir -p public
    - mv ${EXPORT_NAME}_web/** ./public
  artifacts:
    paths:
      - public
  only: 
    - master

# # Itch.io Deploy
# itchio:linux:
#   stage: deploy
#   script:
#     - butler push ./${EXPORT_NAME}_linux $ITCHIO_USERNAME/$ITCHIO_GAME:linux
#   dependencies:
#     - linux
#   only: 
#     - master

# itchio:windows:
#   stage: deploy
#   script:
#     - butler push ./${EXPORT_NAME}_windows $ITCHIO_USERNAME/$ITCHIO_GAME:windows
#   dependencies:
#     - windows
#   only: 
#     - master

# itchio:macosx:
#   stage: deploy
#   script:
#     - butler push ./${EXPORT_NAME}_mac $ITCHIO_USERNAME/$ITCHIO_GAME:mac
#   dependencies:
#     - mac
#   only: 
#     - master

# itchio:html:
#   stage: deploy
#   script:
#     - butler push ./${EXPORT_NAME}_web $ITCHIO_USERNAME/$ITCHIO_GAME:html
#   dependencies:
#     - web
#   only: 
#     - master
