image: barichello/godot-ci:3.2.3
# Cache imported assets between runs
cache:
  key: import-assets
  paths:
    - .import/
stages:
  - export
  - deploy
variables:
  EXPORT_NAME: titan_tactics

windows:
  stage: export
  script:
    - mkdir -v -p ${EXPORT_NAME}_windows
    - godot -v --export "Windows Desktop" ${EXPORT_NAME}_windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - ${EXPORT_NAME}_windows

windows_debug:
  stage: export
  script:
    - mkdir -v -p ${EXPORT_NAME}_windows_debug
    - godot -v --export-debug "Windows Desktop" ${EXPORT_NAME}_windows_debug/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - ${EXPORT_NAME}_windows_debug

linux:
  stage: export
  script:
    - mkdir -v -p ${EXPORT_NAME}_linux
    - godot -v --export "Linux/X11" ${EXPORT_NAME}_linux/$EXPORT_NAME.x86_64
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - ${EXPORT_NAME}_linux

mac:
  stage: export
  script:
    - mkdir -v -p ${EXPORT_NAME}_mac
    - godot -v --export "Mac OSX" ${EXPORT_NAME}_mac/$EXPORT_NAME.zip
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - ${EXPORT_NAME}_mac

# Itch.io Deploy
itchio:linux:
  stage: deploy
  script:
    - butler push ./${EXPORT_NAME}_linux $ITCHIO_USERNAME/$ITCHIO_GAME:linux
  dependencies:
    - linux
  only: 
    - master

itchio:windows:
  stage: deploy
  script:
    - butler push ./${EXPORT_NAME}_windows $ITCHIO_USERNAME/$ITCHIO_GAME:windows
  dependencies:
    - windows
  only: 
    - master

itchio:macosx:
  stage: deploy
  script:
    - butler push ./${EXPORT_NAME}_mac $ITCHIO_USERNAME/$ITCHIO_GAME:mac
  dependencies:
    - mac
  only: 
    - master
